######################################################################
##
## Filename: additioneur_tb.udo
## Created on: Fri Nov 26 13:36:03 Europe de l’Ouest 2010
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
