--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design_ip_dcf_77
-- HDL library   : design_ip_dcf_77
-- Host name     : INF13-MEIERV
-- User name     : vincent.meier
-- Time stamp    : Mon Jun 08 15:29:19 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design_ip_dcf_77.amp_int
-- Last modified : Sun Jun 07 21:42:17 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity amp_int is
  port (
    clk       : in     std_logic;
    reset_n   : in     std_logic;
    start_acq : out    std_logic;
    stop      : in     std_logic);
end entity amp_int;

--------------------------------------------------------------------------------
-- Object        : Architecture design_ip_dcf_77.amp_int.rtl
-- Last modified : Sun Jun 07 21:42:17 2015.
--------------------------------------------------------------------------------


architecture rtl of amp_int is

signal signal_int_latch	:std_logic;

begin

process (clk,reset_n)
begin
  IF reset_n = '0' THEN
    signal_int_latch <= '0';    
  ELSIF clk'EVENT AND clk = '1' THEN
    signal_int_latch <= stop;
  END IF;
end process;

start_acq <= signal_int_latch OR  stop;



end architecture rtl ; -- of amp_int

