--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design_dcf_complete
-- HDL library   : design_dcf_complete
-- Host name     : INF13-MEIERV
-- User name     : vincent.meier
-- Time stamp    : Mon Jun 08 15:29:19 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design_dcf_complete.BaudRateCounter
-- Last modified : Mon Jun 08 01:14:22 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity BaudRateCounter is
  port (
    clk          : in     std_logic;
    en_16_x_baud : out    std_logic;
    reset_n      : in     std_logic;
    start_tr     : in     std_logic;
    uart_cs      : in     std_logic);
end entity BaudRateCounter;

--------------------------------------------------------------------------------
-- Object        : Architecture design_dcf_complete.BaudRateCounter.rtl
-- Last modified : Mon Jun 08 01:14:22 2015.
--------------------------------------------------------------------------------


architecture rtl of BaudRateCounter is

signal counter : std_logic_vector(7 DOWNTO 0); --Signal interne pour compteur

begin 

P1:process (clk, reset_n)           

	begin                  
	
	if(reset_n = '0') then -- reset asynchrone
		counter  <= (OTHERS => '0'); 
		
	elsif(clk'EVENT and clk = '1') then   
	  if counter = x"16" then -- si = 22
	   	   counter <= (OTHERS => '0');  
	   	   en_16_x_baud <= '1';  
	  else
		   counter <= STD_LOGIC_VECTOR(UNSIGNED(counter) + 1); 
		   en_16_x_baud <= '0';	
	  end if; 
			
	end if;	  
		
end process;    

end architecture rtl ; -- of BaudRateCounter

