--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design_dcf_complete
-- HDL library   : design_dcf_complete
-- Host name     : INF13-BENSALAHM
-- User name     : mohammed.bensalah
-- Time stamp    : Sun Jun 07 13:18:33 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design_dcf_complete.DCF77_Receiver_tb
-- Last modified : Sat Jun 06 15:14:38 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity DCF77_Receiver_tb is
end entity DCF77_Receiver_tb;

--------------------------------------------------------------------------------
-- Object        : Architecture design_dcf_complete.DCF77_Receiver_tb.behaviour
-- Last modified : Sat Jun 06 15:14:38 2015.
--------------------------------------------------------------------------------

architecture behaviour of DCF77_Receiver_tb is

  signal dcf_77_in        : std_logic;
  signal clk              : std_logic;
  signal reset_n          : std_logic;
  signal FrameComplete    : std_logic;
  signal FrameIncorrect   : std_logic;
  signal FrameReception   : std_logic;
  signal switch           : std_logic_vector(1 downto 0);
  signal serial_out       : std_logic;
  signal TEST             : std_logic;
  signal debug_leds       : std_logic_vector(7 downto 0);
  signal program_counter  : std_logic_vector(7 downto 0);
  signal time_bc_7seg_lsb : std_logic_vector(6 downto 0);
  signal time_bc_7seg_msb : std_logic_vector(6 downto 0);

  component DCF77_Receiver
    port (
      FrameComplete    : out    std_logic;
      FrameIncorrect   : out    std_logic;
      FrameReception   : out    std_logic;
      TEST             : in     std_logic;
      clk              : in     std_logic;
      dcf_77_in        : in     std_logic;
      debug_leds       : out    std_logic_vector(7 downto 0);
      program_counter  : out    std_logic_vector(7 downto 0);
      reset_n          : in     std_logic;
      serial_out       : out    std_logic;
      switch           : in     std_logic_vector(1 downto 0);
      time_bc_7seg_lsb : out    std_logic_vector(6 downto 0);
      time_bc_7seg_msb : out    std_logic_vector(6 downto 0));
  end component DCF77_Receiver;

  component DCF77_Receiver_stimuli
    port (
      FrameComplete    : in     std_logic;
      FrameIncorrect   : in     std_logic;
      FrameReception   : in     std_logic;
      TEST             : out    std_logic;
      clk              : out    std_logic;
      dcf_77_in        : out    std_logic;
      debug_leds       : in     std_logic_vector(7 downto 0);
      program_counter  : in     std_logic_vector(7 downto 0);
      reset_n          : out    std_logic;
      serial_out       : in     std_logic;
      switch           : out    std_logic_vector(1 downto 0);
      time_bc_7seg_lsb : in     std_logic_vector(6 downto 0);
      time_bc_7seg_msb : in     std_logic_vector(6 downto 0));
  end component DCF77_Receiver_stimuli;

begin

  dut: DCF77_Receiver
    port map(
      FrameComplete    => FrameComplete,
      FrameIncorrect   => FrameIncorrect,
      FrameReception   => FrameReception,
      TEST             => TEST,
      clk              => clk,
      dcf_77_in        => dcf_77_in,
      debug_leds       => debug_leds,
      program_counter  => program_counter,
      reset_n          => reset_n,
      serial_out       => serial_out,
      switch           => switch,
      time_bc_7seg_lsb => time_bc_7seg_lsb,
      time_bc_7seg_msb => time_bc_7seg_msb);

  stimuli: DCF77_Receiver_stimuli
    port map(
      FrameComplete    => FrameComplete,
      FrameIncorrect   => FrameIncorrect,
      FrameReception   => FrameReception,
      TEST             => TEST,
      clk              => clk,
      dcf_77_in        => dcf_77_in,
      debug_leds       => debug_leds,
      program_counter  => program_counter,
      reset_n          => reset_n,
      serial_out       => serial_out,
      switch           => switch,
      time_bc_7seg_lsb => time_bc_7seg_lsb,
      time_bc_7seg_msb => time_bc_7seg_msb);
end architecture behaviour ; -- of DCF77_Receiver_tb

