--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design_dcf_complete
-- HDL library   : design_dcf_complete
-- Host name     : INF13-MEIERV
-- User name     : vincent.meier
-- Time stamp    : Mon Jun 08 15:29:19 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design_dcf_complete.inversor
-- Last modified : Sun Jun 07 17:05:02 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity inversor is
  port (
    input : in     std_logic;
    reset : out    std_logic);
end entity inversor;

--------------------------------------------------------------------------------
-- Object        : Architecture design_dcf_complete.inversor.rtl
-- Last modified : Sun Jun 07 17:05:02 2015.
--------------------------------------------------------------------------------


architecture rtl of inversor is

begin

reset <= not input;           

end architecture rtl ; -- of inversor

