--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : INF13-MEIERV
-- User name     : vincent.meier
-- Time stamp    : Tue Jun 02 10:12:22 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.inversor
-- Last modified : Mon May 04 19:58:00 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity inversor is
  port (
    input   : in     std_logic;
    reset_n : out    std_logic);
end entity inversor;

--------------------------------------------------------------------------------
-- Object        : Architecture design.inversor.rtl
-- Last modified : Mon May 04 19:58:00 2015.
--------------------------------------------------------------------------------


architecture rtl of inversor is

begin

reset_n <= not input;           

end architecture rtl ; -- of inversor

