--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : INF13-MEIERV
-- User name     : vincent.meier
-- Time stamp    : Tue Jun 02 10:12:22 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.mux_dcf_test
-- Last modified : Mon Jun 01 11:53:30 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mux_dcf_test is
  port (
    TEST                : in     std_logic;
    adress_mux_dcf_test : in     std_logic_vector(1 downto 0);
    buffer_full         : in     std_logic;
    data_dcf            : in     std_logic_vector(7 downto 0);
    data_out            : out    std_logic_vector(7 downto 0);
    start_acq           : in     std_logic);
end entity mux_dcf_test;

--------------------------------------------------------------------------------
-- Object        : Architecture design.mux_dcf_test.rtl
-- Last modified : Mon Jun 01 11:53:30 2015.
--------------------------------------------------------------------------------


architecture rtl of mux_dcf_test is

signal test_vector : std_logic_vector(7 downto 0):=x"00";
             
begin

WITH adress_mux_dcf_test SELECT
	 data_out <= data_dcf								WHEN "00",
	 			 test_vector(7 downto 1) & start_acq 	WHEN "01",
	 			 test_vector(7 downto 1) & buffer_full 	WHEN "10",
	 			 test_vector(7 downto 1) & TEST			WHEN "11",
	 			 x"FF"			                        WHEN OTHERS;
	 
	 			 	


end architecture rtl ; -- of mux_dcf_test

