--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : INF13-BENSALAHM
-- User name     : mohammed.bensalah
-- Time stamp    : Fri Jun 05 19:19:26 2015
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.mux_dcf_test
-- Last modified : Fri Jun 05 19:04:11 2015.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mux_dcf_test is
  port (
    TEST                : in     std_logic;
    adress_mux_dcf_test : in     std_logic_vector(1 downto 0);
    data_dcf            : in     std_logic_vector(7 downto 0);
    data_out            : out    std_logic_vector(7 downto 0));
end entity mux_dcf_test;

--------------------------------------------------------------------------------
-- Object        : Architecture design.mux_dcf_test.rtl
-- Last modified : Fri Jun 05 19:04:11 2015.
--------------------------------------------------------------------------------


architecture rtl of mux_dcf_test is

signal test_vector : std_logic_vector(7 downto 0):=x"00";
             
begin

WITH adress_mux_dcf_test SELECT
	 data_out <= test_vector(7 downto 1) & TEST 	WHEN "01",
	 			 data_dcf WHEN OTHERS;
	 
	 			 	


end architecture rtl ; -- of mux_dcf_test

