--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.0 Revision 2 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : NE-EIN-138-00
-- User name     : yves.meyer
-- Time stamp    : Wed Dec 11 15:16:27 2013
--
-- Designed by   : Y.Meyer
-- Company       : Haute Ecole ARC
-- Project info  : Additionneur PicoBlaze
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.registres
-- Last modified : Wed Dec 04 15:54:06 2013.
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity registres is
  port (
    carry_out    : out    std_logic;
    clk          : in     std_logic;
    out_port     : in     std_logic_vector(7 downto 0);
    port_id      : in     std_logic_vector(7 downto 0);
    reset_n      : in     std_logic;
    resultat     : out    std_logic_vector(7 downto 0);
    write_strobe : in     std_logic);
end entity registres;

--------------------------------------------------------------------------------
-- Object        : Architecture design.registres.behaviour
-- Last modified : Wed Dec 04 15:54:06 2013.
--------------------------------------------------------------------------------


architecture behaviour of registres is

begin

p1:PROCESS (clk,reset_n)
BEGIN
	IF reset_n = '0' THEN
		 resultat <= (OTHERS => '0');
		 carry_out <= '0';
	ELSIF clk'EVENT AND clk = '1' THEN
		IF WRITE_STROBE = '1' THEN
			CASE PORT_ID IS
				WHEN X"03" =>	 
					 resultat <= OUT_PORT;
				WHEN X"04" =>	 
					 carry_out <=	OUT_PORT(0);
				WHEN OTHERS => NULL;
			END CASE;
		END IF;
	END IF;
END PROCESS;

end architecture behaviour ; -- of registres

